### ISSUE TITLE
Error when running video caption model inference. 

### ISSUE THREAD

**Issue by Marlod390** [snap-research/Panda-70M#11]
Thank you for your great work. But when I ran the video caption model according to the tutorial, the following error occurred:

`Traceback (most recent call last):
  File "/home/markusc/github/Panda-70M/captioning/inference.py", line 27, in <module>
    cfg = Config(args)
  File "/home/markusc/github/Panda-70M/captioning/video_llama/common/config.py", line 25, in __init__
    user_config = self._build_opt_list(self.args.options)
AttributeError: 'Namespace' object has no attribute 'options'`

How can I fix the problem?
Maybe line 25 `user_config = self._build_opt_list(self.args.options)` in config.py should be replaced with `user_config = self._build_opt_list(self.args.cfg_path)`?

**Comment by tsaishien-chen** [comment]
Thanks for letting me know the bug. I have fixed it by adding [these](https://github.com/snap-research/Panda-70M/blob/603aa1a586da224b2a4c0c54b139f678f307c682/captioning/inference.py#L26-L32).

**Comment by johndpope** [comment]
@tsaishien-chen  - random question do you guys have a SAN to store all these videos? or just use a bucket? s3 or minio?
I'm was thinking of buying a couple of 12tb drives and "gluing" them together with ReFS to have 36tb drive.. but looks fragile.
