### ISSUE TITLE
Single Instance?

### ISSUE THREAD

**Issue by kuno989** [snap-research/Panda-70M#27]
Did you download it in a single instance or did you download it in parallel using spark or something?
There are many ways to go with video2dataset, and I'd be interested in your thoughts before I try to download it.

**Comment by tsaishien-chen** [comment]
Hi @kuno989,
Like [this line](https://github.com/snap-research/Panda-70M/blob/85a178ae961e51b0058ae3a4aba1dbf43521b813/dataset_dataloading/video2dataset/video2dataset/configs/panda_70M.yaml#L24) in the config file, the current codebase uses Python in-built `multiprocessing` for parallel downloading.
Video2dataset tool also supports different ways to achieve parallel downloading. Please can check [here](https://github.com/iejMac/video2dataset/blob/main/video2dataset/distributor.py).
Hope this answer your question!
