### ISSUE TITLE
Could you please provide a way to download the processed videos?

### ISSUE THREAD

**Issue by Kyfafyd** [snap-research/Panda-70M#30]
RT.
As I may not have enough space to download all raw videos, could you zip the processed videos and captions for downloading? A subset is also fine!

**Comment by tsaishien-chen** [comment]
Hi @Kyfafyd,
Thanks for your interest about our dataset! Unfortunately, we are not allowed to distribute any videos.
I suggest you download the testing and validation set first, as they are relatively small.
