### ISSUE TITLE
What's your criteria to select 3.8M high-quality videos from HDVILA-100M?

### ISSUE THREAD

**Issue by vinjn** [snap-research/Panda-70M#33]
Thanks in advance,
Jing.

**Comment by tsaishien-chen** [comment]
Hi @vinjn,
Thanks for your interests in our dataset!
HDVILA-100M includes 100M video clips from 3.8M high-quality long videos, so we use all of the long videos in HDVILA-100M without discarding any of them.

**Comment by vinjn** [comment]
Thanks, how did you define "long videos"?

**Comment by tsaishien-chen** [comment]
Hi @vinjn,
Please refer to the [original HDVILA-100M paper](https://openaccess.thecvf.com/content/CVPR2022/papers/Xue_Advancing_High-Resolution_Video-Language_Representation_With_Large-Scale_Video_Transcriptions_CVPR_2022_paper.pdf). It includes how those 3M videos are collected.

**Comment by vinjn** [comment]
Awesome, thx
