### ISSUE TITLE
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x1528be026f50>, 'Connection to rr2---sn-ibj-i3bez.googlevideo.com timed out. (connect timeout=20.0)')

### ISSUE THREAD

**Issue by syguan96** [snap-research/Panda-70M#36]
Hi @tsaishien-chen  @AliaksandrSiarohin , thanks for releasing this high-quality video dataset. When I downloaded this dataset, I met this problem. I wonder it's a bug in video2dataset, or just the problem of VPN.

[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x1528be026f50>, 'Connection to rr2---sn-ibj-i3bez.googlevideo.com timed out. (connect timeout=20.0)')

**Comment by kuno989** [comment]
I think it's a proxy or vpn problem.

**Comment by tsaishien-chen** [comment]
Hi @syguan96,
Thanks for your interest about this dataset!
Could you please try to download the dataset with another proxy or using VPN and let me know whether this can help?

**Comment by syguan96** [comment]
Hi Chen, thanks for your reply! It recovered after several hours.

**Comment by nankepan** [comment]
how to use proxy? could you give an example?
